// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayBridge.Infrastructure.Data;

#nullable disable

namespace PayBridge.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508173152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PayBridge.Features.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LinkToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link_token");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_contracts_client_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_contracts_user_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("PayBridge.Features.Users.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("GhanaCardIdBack")
                        .HasColumnType("text")
                        .HasColumnName("ghana_card_id_back");

                    b.Property<string>("GhanaCardIdFront")
                        .HasColumnType("text")
                        .HasColumnName("ghana_card_id_front");

                    b.Property<string>("GhanaCardIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("ghana_card_id_number");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kyc_status");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("UserId")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("PayBridge.Features.Contracts.Contract", b =>
                {
                    b.HasOne("PayBridge.Features.Users.UserProfile", "ClientProfile")
                        .WithMany("ClientContracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contracts_user_profiles_client_id");

                    b.HasOne("PayBridge.Features.Users.UserProfile", "UserProfile")
                        .WithMany("UserContracts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_user_profiles_user_id");

                    b.Navigation("ClientProfile");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("PayBridge.Features.Users.UserProfile", b =>
                {
                    b.Navigation("ClientContracts");

                    b.Navigation("UserContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
