// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayBridge.Infrastructure.Data;

#nullable disable

namespace PayBridge.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508183338_AddPaymentAccountTable")]
    partial class AddPaymentAccountTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PayBridge.Features.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LinkToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link_token");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_contracts_client_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_contracts_user_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("PayBridge.Features.Contracts.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_milestones_contract_id");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("PayBridge.Features.Payments.Models.PaymentAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("account_balance");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_code");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_accounts");

                    b.HasIndex("userId")
                        .HasDatabaseName("ix_payment_accounts_user_id");

                    b.ToTable("payment_accounts", (string)null);
                });

            modelBuilder.Entity("PayBridge.Features.Users.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("GhanaCardIdBack")
                        .HasColumnType("text")
                        .HasColumnName("ghana_card_id_back");

                    b.Property<string>("GhanaCardIdFront")
                        .HasColumnType("text")
                        .HasColumnName("ghana_card_id_front");

                    b.Property<string>("GhanaCardIdNumber")
                        .HasColumnType("text")
                        .HasColumnName("ghana_card_id_number");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kyc_status");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("UserId")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("PayBridge.Features.Contracts.Contract", b =>
                {
                    b.HasOne("PayBridge.Features.Users.UserProfile", "ClientProfile")
                        .WithMany("ClientContracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contracts_user_profiles_client_id");

                    b.HasOne("PayBridge.Features.Users.UserProfile", "UserProfile")
                        .WithMany("UserContracts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_user_profiles_user_id");

                    b.Navigation("ClientProfile");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("PayBridge.Features.Contracts.Milestone", b =>
                {
                    b.HasOne("PayBridge.Features.Contracts.Contract", "Contract")
                        .WithMany("Milestones")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_contracts_contract_id");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("PayBridge.Features.Payments.Models.PaymentAccount", b =>
                {
                    b.HasOne("PayBridge.Features.Users.UserProfile", "UserProfile")
                        .WithMany("PaymentAccounts")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_accounts_user_profiles_user_id");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("PayBridge.Features.Contracts.Contract", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("PayBridge.Features.Users.UserProfile", b =>
                {
                    b.Navigation("ClientContracts");

                    b.Navigation("PaymentAccounts");

                    b.Navigation("UserContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
